services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: auris
      POSTGRES_PASSWORD: auris123
      POSTGRES_DB: auris_core
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    command: npm run start

volumes:
  pgdata:
